stages:
  - Test and Lint   # run on unit test 
  - Build and Push  # build docker images and push ECR
  - Staging Plan
  - Staging Apply
  - Production Plan
  - Production Apply
  - Destroy

Test and Lint:
  stage: Test and Lint
  script:
    - echo "Test and Lint"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production)$/ || $CI_COMMIT_BRANCH = ~ /^(main|production)$/'
    
Validate Terraform:
  stage: Test and Lint
  script:
    - echo "Validate Terraform"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production)$/ || $CI_COMMIT_BRANCH = ~ /^(main|production)$/'

Build and Push:
  stage: Build and Push
  script:
    - echo " Build and Push Docker image"
  rules:
    - if: '$CI_COMMIT_BRANCH= ~ /^(main|production)$/'

Staging Plan:
  stage: Staging Plan
  script:
    echo "Run Terrform Plan for staging"
  rules:
    - if: '$CI_COMMIT_BRANCH= ~ /^(main|production)$/'

Staging Apply:
  stage: Staging Apply
  script:
    echo "Run Terrform Plan for staging"
  rules:
    - if: '$CI_COMMIT_BRANCH= ~ /^(main|production)$/'


Production Plan:
  stage: Production Plan
  script:
    echo "Run Terrform Plan for Production"
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'

Production Apply:
  stage: Production Apply
  script:
    echo "Run Terrform Plan for Production"
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'

Staging Destroy:
  stage: Destroy
  script:
    echo "Run Terraform Desroy for staging"
  rules:
    - if: '$CI_COMMIT_BRANCH = ~/^(master|production)$/'
      when: manual

Production Destroy:
  stage: Destroy
  script:
    echo "Run Terraform Desroy for production"
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
      when: manual